name: Build common setup

inputs:
  contribsys-credentials:
    description: "Contribsys credentials"
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - run: pnpm i
      shell: bash

    - run: pnpm vercel link --scope anti-work --yes --token ${{ secrets.VERCEL_ENV_KEY }} && pnpm vercel env pull .env --token ${{ secrets.VERCEL_ENV_KEY }} && ln -s $PWD/.env ./apps/next/.env
      shell: bash

    - uses: ruby/setup-ruby@v1
      with:
        working-directory: apps/rails
        bundler-cache: true # runs "bundle install" and caches installed gems automatically
